name: Build project

on:
  workflow_dispatch:
    inputs:
      uploadArtifacts:
        description: "Define whether or not to upload the artifacts"
        type: boolean
        required: false
        default: false
      includeReports:
        description: "Shall report output be included in the uploaded artifacts?"
        type: boolean
        required: false
        default: true
  workflow_call:
    inputs:
      uploadArtifacts:
        type: boolean
        required: false
        default: false
      includeReports:
        type: boolean
        required: false
        default: true
    secrets:
      GPG_SECRET_KEY:
        required: true
      GPG_SECRET_KEY_PASSWORD:
        required: true

env:
  JAVA_VERSION: 16

# based https://docs.github.com/en/actions/guides/building-and-testing-java-with-gradle
jobs:
  build-project:
    runs-on: ubuntu-latest
    name: Build with Java
    steps:
      - name: Cache Dependencies
        uses: actions/cache@v3.0.5
        with:
          key: maven-dependencies
          path: ~/.m2/repository
      - name: Check out
        uses: actions/checkout@v3.0.2
      - name: Set up JDK ${{env.JAVA_VERSION}}
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: ${{env.JAVA_VERSION}}
          gpg-private-key: ${{ secrets.GPG_SECRET_KEY }}
          gpg-passphrase: GPG_PASSPHRASE
      - name: "Maven: Clean, Build, Install"
        run: |
          set -o errexit -o pipefail
          mvn clean install --activate-profiles dirty,dirty-package --update-snapshots --batch-mode --show-version 2>&1 | tee mvnout.txt
          set +o errexit +o pipefail
      - name: "Maven: Test, Verify"
        run: |
          set -o errexit -o pipefail
          gpgParameter="-Dskip.gpg=true"
          if [ ${{inputs.uploadArtifacts}} ]; then
            gpgParameter=""
          fi
          echo mvn test verify --batch-mode --show-version $gpgParameter
          mvn test verify --batch-mode --show-version $gpgParameter 2>&1 | tee --append mvnout.txt
          set +o errexit +o pipefail
        env:
          # GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GPG_PASSPHRASE: ${{ secrets.GPG_SECRET_KEY_PASSWORD }}
      - name: Check Output
        shell: bash {0}
        run: |
          chmod +x ./target/mvn-suppressions-parent.sh
          mvnout=`cat mvnout.txt | grep --perl-regexp "(?i)\\[(ERR|WARN)" | ./target/mvn-suppressions-parent.sh "$JDK_VERSION"`
          
          if [ -n "${mvnout}" ]; then
            echo "[ERROR] The Maven output contains the following unknown warnings and errors:" >&2
            echo "${mvnout}" >&2
            false
          else
            echo "[INFO] No unknown warnings and errors found."
            echo "${mvnout}" >&2
          fi
        env:
          JDK_VERSION: ${{env.JAVA_VERSION}}
      - name: Echo
        run: |
          echo reports: ${{inputs.includeReports}} , upload: ${{inputs.uploadArtifacts}}
      - name: "Maven: Site"
        if: ${{ inputs.includeReports }}
        run: |
          set -o errexit -o pipefail
          mvn site --batch-mode
          set +o errexit +o pipefail
      - name: Upload artifacts
        if: ${{ inputs.uploadArtifacts }}
        uses: actions/upload-artifact@v3
        with:
          name: site
          path: ./target/*-full.jar
