name: Test myself

on:
  workflow_dispatch:

jobs:
  delete:
    runs-on: ubuntu-latest
    name: "Delete Docker images"
    steps:
      - name: "Delete them"
        uses: noxone/docker-image-deleter@refs/heads/main
        with:
          url: "https://hub.docker.com/v2"
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          token: ${{ secrets.DOCKERHUB_TOKEN }}
          tagsToKeep: 11
          repositories: regexgenerator

