name: Test myself

on:
  workflow_dispatch:

jobs:
  delete:
    runs-on: ubuntu-latest
    name: "Delete Docker images"
    steps:
      - name: "Delete them"
        uses: noxone/docker-image-deleter@5e8496142a38ef9247ec30977cbc27443ef49612
        with:
          url: "https://hub.docker.com/v2"
          username: ${{ secrets.GITHUB_USERNAME }}
          token: ${{ secrets.GITHUB_TOKEN }}
          tagsToKeep: 11
          repositories: regexgenerator

