
name: Build and test project

on:
  push:
    branches-ignore:
    - "main"
  pull_request:

jobs:
  build-project:
    name: "Build project"
    uses: ./.github/workflows/build-project.yml
    with:
      uploadArtifacts: true
      includeReports: false
    secrets:
      GPG_SECRET_KEY: ${{ secrets.GPG_SECRET_KEY }}
      GPG_SECRET_KEY_PASSWORD: ${{ secrets.GPG_SECRET_KEY_PASSWORD }}

#  build-docker:
#    needs: build-project
#    name: Build Docker images
#    uses: ./.github/workflows/build-docker.yml
#    with:
#      appEnvironment: "github"
#      pushImages: false
#   secrets:
#     DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
#     DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
